### PR TITLE
Use enumerate type to replace zorder

### LINKED ISSUE #33: imposm3: zorder type is deprecated and will be removed
Warning when using _imposm3-mapping.json_ with latest version of imposm3 (_imposm3-0.2.0dev-20160615-d495ca4-linux-x86-64_) :
`[INFO] [mapping] warn: zorder type is deprecated and will be removed. See enumerate type.`

imposm3 documentation : https://imposm.org/docs/imposm3/latest/mapping.html#column-types

### PR DESCRIPTION
**Pull request by sgrossberndt**
Update according to https://github.com/omniscale/imposm3/commit/9e125aee02b2193f1c246c69eafbd242eeeb070a

Fixes #33

### CODE REVIEW

**Comment by yjacolin** [comment]
Does imposm support this? Or only imposm3?

**Comment by sgrossberndt** [comment]
Only imposm3 supports this AFAIK, but also only imposm3 deprecated the zorder type and this patch only changes the imposm3 mapping.

**Comment by sgrossberndt** [comment]
No support for enumerate in [imposm](https://github.com/omniscale/imposm/search?utf8=%E2%9C%93&q=enumerate)  but in [imposm3](https://github.com/omniscale/imposm/search?utf8=%E2%9C%93&q=enumerate)

**Comment by yjacolin** [comment]
of course! Sorry didn't check the filename! Side note: did you subscribe to the mapserver-dev mailing list? I would like to ask to give you commit right on the repository.

**Comment by sgrossberndt** [comment]
I did not know of it, just subscribed. Thanks for the trust - I think it's good to have at least a four-eyes-principle on the commits, but would be honored to review yours too and further help with the development of basemaps.

**Pull request merged**
